services:
  simpletododb:
    container_name: simpletododb
    environment:
      SA_PASSWORD: '@Password123'
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - db_volume:/var/opt/mssql
